### ISSUE TITLE
gnome-shell 3.36 crashing on screen lock/unlock

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#124]
gnome-shell 3.36 is crashing when gTile is enabled, when locking or unlocking screen.
To help debugging, please enable debug in gTile, and post here journalctl|grep gTile.

**Comment by topjor** [comment]
Repost + edits: I also use manjaro and updated via tty with no graphical environment active so the recommended way. I am using wayland and I can confirm its gTile or a combination of gTile and another extension that causes crashes upon unlocking, for me it is after unlocking, I tried a few times and if gTile is enabled it crashes, but weirdly, only when the extension is active when logging in, when activating the extension after I am logged in, this issue does not seem to occur for some reason. (I just installed the git master version)

Edit: I only have this issue when clicking the menu's in the the top bar after a unlock  or at the unlock screen when locked, I can interact with other things fine, but once I click a menu up top it crashes (have not yet looked at logs, first narrowing down when it happens consistently)
Some other menu's from other extensions and the activities once opened using the shortcut don't crash it as consistently, but still crash it quite frequently.
Also, only sometimes it crashes directly upon unlocking, but not consistently or frequently

I will see about grabbing some logs tomorrow as I have to get up on time tomorrow and its already getting late

OS: Manjaro
Display server: Wayland
Other extensions: yes (have not yet tried without others)

**Comment by danleepw** [comment]
After using the latest version (V34) of gTile, it seems my lock screen crash is no longer because of gTile. I am suspecting that my current crash is due to telegram desktop app which has system tray and event notification. Do you guys also have some apps which are using system tray and event notification too?

**Comment by yochananmarqos** [comment]
GNOME Shell has been crashing for me as well on Manjaro after resuming from suspend, but I have no log results for `journalctl | grep gTile` since [this commit](20afc664288dbf5dde8c2f16601172eef177b4ae).

**Comment by murbanowicz** [comment]
Omg. Is this issue really related to gTile? I was Googling all evening for this issue, but I didn't expect it can be gTile related...

**Comment by scherepanov** [comment]
Hint: to get debug from gTile, it have to be enabled in preferences and session login/logout.
I do not see crash of gnome-shell on Fedora, but seems to be it is related panel button that have been written many years ago and uses outdated API. I will try to rewrite it using current API, will see if it will help.

**Comment by topjor** [comment]
There is no gTile specific logs that I am able to exctract as gnome-shell is fully crashing and dying, I did see the debug log of gTile startup up

**Comment by topjor** [comment]
> Hint: to get debug from gTile, it have to be enabled in preferences and session login/logout.
> I do not see crash of gnome-shell on Fedora, but seems to be it is related panel button that have been written many years ago and uses outdated API. I will try to rewrite it using current API, will see if it will help.

I have commented out all the `launcher` and `gtile button` stuff, later also most of the hotkey stuff and it still crashes

Also after disabling all other extensions it now crashes whenever I try and wake it again after locking

**Comment by danleepw** [comment]
I agree that those crashes may be not related to any extension but gnome-shell itself. I am quite surprised that no related issue can be found the gitlab of gnome.

**Comment by topjor** [comment]
I only seem to have this issue when gTile is enabled thats probably why, maby it has to do with some api's that are called that trigger some internal state that results eventually in these crashes upon unlocking / waking the screen. This also only happens when gTile is loaded when logging in initially and not when enabling it after logging in.

**Comment by danleepw** [comment]
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1868440
https://bugzilla.redhat.com/show_bug.cgi?id=1812781

**Comment by scherepanov** [comment]
Nice catch @danleepw . Yes, it appears to be caused by gnome-shell bug. Trace is same as observed here.
Will wait for a fix on their side.

**Comment by danleepw** [comment]
I suspect that gnome-shell 3.36.0 has some changes on system tray handling. Any app or extension using system tray may trigger a crash.

**Comment by danleepw** [comment]
Finally, found this bug report: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2541

**Comment by tomWhilbert** [comment]
Here is my dump:
`_getInvisibleBorderPadding@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:511:32
                                                 move_resize_window_with_margins@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:551:29
                                                 AutoTileNCols@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1465:5
                                                 _onButtonPress@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1435:9
Mar 31 20:04:42 arch.localhost gnome-shell[7163]: st_widget_get_theme_node called on the widget [0x561eae98f5c0 StBoxLayout.grid-panel ("Firefox - gnome-shell 3.36 crashing on screen lock/unlock · Issue #124 · gTile/gTile - Mozilla Firefox")] which is not in the stage.
Mar 31 20:04:42 arch.localhost gnome-shell[7163]: st_widget_get_theme_node called on the widget [0x561eae98f5c0 StBoxLayout.grid-panel ("Firefox - gnome-shell 3.36 crashing on screen lock/unlock · Issue #124 · gTile/gTile - Mozilla Firefox")] which is not in the stage.
Mar 31 20:04:42 arch.localhost gnome-shell[7163]: st_widget_get_theme_node called on the widget [0x561eae98f5c0 StBoxLayout.grid-panel ("Firefox - gnome-shell 3.36 crashing on screen lock/unlock · Issue #124 · gTile/gTile - Mozilla Firefox")] which is not in the stage.
Mar 31 20:04:42 arch.localhost gnome-shell[7163]: st_widget_get_theme_node called on the widget [0x561eae98f5c0 StBoxLayout.grid-panel ("Firefox - gnome-shell 3.36 crashing on screen lock/unlock · Issue #124 · gTile/gTile - Mozilla Firefox")] which is not in the stage.`

**Comment by jdus** [comment]
> https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1868440
> https://bugzilla.redhat.com/show_bug.cgi?id=1812781

Yes, that's exactly it. Similar to the stack trace I have already posted in the previous issue.

**Comment by scherepanov** [comment]
It appears gnome-shell 3.36 have a bug with St library.
I think we need to wait till it will be fixed in gnome-shell.
In theory, it is possible to rewrite gTile GUI without St. It is rather big task. All fancy animated things will be lost. I do not think it is a good idea.

**Comment by sroebuck** [comment]
Until two days ago I was experiencing this bug in the Ubuntu 20.04 beta but something updated since then appears to have fixed the problem.  Either that or it was caused by turning on Fractional Scaling which I turned off again yesterday.

**Comment by elpraga** [comment]
My Ubuntu 20.04 bug here:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1871063

more here:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1868440

I'll try to investigate more. 

gTile is one of the best extensions!

**Comment by lillem4n** [comment]
Happening on Gnome 3.36.1 on Arch/Wayland for me to. Hope it gets fixed, will live with the crashes for now, can not live without gTile. :)

**Comment by scherepanov** [comment]
That crashes, in my opinion, happens due to changes in gnome-shell core - it became intolerable to "old" way of doing styleclasses. And, gTile was written very long ago, using API that now is not tolerated.
Fix seems to be not extremely hard, you need to rewrite two components using "modern" way.
I will try, as soon as I will get some time. Unusually busy recently.

**Comment by topjor** [comment]
as a workaround for some reason on my machine, it would never crash when enabled manualy after login.
but this would mean that you would also need to disable it everytime you logout and everytime you login

**Comment by sroebuck** [comment]
Okay, I'm fairly certain that this bug has been fixed by the latest updates for Ubuntu 20.04 beta.

Up until now I could consistently reproduce the bug on Ubunto 20.04 beta by turning on the gTile extension, logging out and back in then forcing a screen lock and trying to log back in.

The fault, as well as crashing gnome-shell would manifest itself in the logs as line like this:

```
gnome-shell[7546]: segfault at 0 ip 00007f139e71daac sp 00007ffe519428a0 error 4 in libst-1.0.so[7f139e6ff000+4b000]
```

Since my `apt upgrade` yesterday afternoon I have not been able to reproduce the fault.

**Comment by danleepw** [comment]
My crash has been fixed since gnome-shell version (1:3.36.1+31+ga6783692c-1) in Manjaro

**Comment by scherepanov** [comment]
Fixed with recent gnome-shell updates

**Comment by elpraga** [comment]
I am still experiencing crashes. No on Lock and unlock, but randomly. They do not appear then gTile is disabled. Could this issue be reopened?

**Comment by kevinhwang91** [comment]
> I am still experiencing crashes. No on Lock and unlock, but randomly. They do not appear then gTile is disabled. Could this issue be reopened?

Me too.
OS: Arch Linux x86_64
Host: XPS 13 9370
Kernel: 5.4.32-1-lts
Uptime: 7 days, 9 hours, 13 mins
Packages: 1244 (pacman)
Shell: zsh 5.8
Resolution: 3840x2160, 2160x3840
DE: GNOME
WM: Mutter
WM Theme: Adwaita
Theme: Arc-Dark-solid [GTK2/3]
Icons: Papirus-Dark [GTK2/3]
CPU: Intel i7-8550U (8) @ 4.000GHz
GPU: Intel UHD Graphics 620
GPU: NVIDIA GeForce GTX 1060 3GB
Memory: 12187MiB / 15711MiB

**Comment by RemiDesgrange** [comment]
Arch did not yet upgrade gnome-shell. It's still version 3.36.1 from March 31th.

**Comment by k4st33l** [comment]
On Arch you can use AUR package gnome-shell-performance for now.

**Comment by yochananmarqos** [comment]
This is happening again with the `gdm` 3.36.2-1 update on Manjaro Linux. I'm using `gnome-shell-extension-gtile-git` 35.r2.g3117c6b.

**Comment by sethgoldin** [comment]
gTile is causing a crash 100% of the time my screen locks. Disabling the extension allows the screen to lock and unlock normally again. Is this the right place to report this or should I post a new issue?

- Fedora release 32
- Kernel 5.6.11-300.fc32.x86_64
- GDM 3.36.2

**Comment by scherepanov** [comment]
That is not a correct statement - lock is always successful first time after login, and crash is always on second lock. As you cannot have more than one crash in session, correct statement would be is that crash is in 50% of locks.
It is upstream problem in gnome-shell and is affecting not only gTile.
That is caused by gTile using nested styles, which is causing incorrect behaviour in libst, which is causing sigabrt and gnome-shell crash. Problem is on upstream gnome-shell 3.36.2, has been reported and fix issued. Fix not yet merged in gnome-shell master (as of day before yesterday, may be merged as of today).
Having this kind of issues is a price of updating your desktop to most recent software versions.
Your options is to wait till path will make it to gnome-shell master, then rolled out to new gnome-shell patch level.
Alternatively, it is possible to modify gTile and remove parent style in around 10 places. That will change gTile GUI in some places and make some GUI states undistinguishable...
Not sure what is right approach in this case. Though I do want to maintain gTile in usable state, it is not obvious how to make it better. Easiest is to sit and wait till fix from upstream will reach distributions.

**Comment by sethgoldin** [comment]
@scherepanov Thanks for this. Happy to wait it out. It's definitely a risk of being on Fedora as opposed to CentOS. 😄

**Comment by marzukia** [comment]
Fedora32 here GNOME shell version 3.36.2, Super + L is crashing gnome-shell when gTile is installed. No issues when I remove it.

**Comment by scherepanov** [comment]
Install gnome-shell 3.36-3 when available, will fix problem

**Comment by yochananmarqos** [comment]
@scherepanov Do you know which commit fixes the issue?

**Comment by scherepanov** [comment]
I know there were one commit to gnome-shell that was fixing an issue. But, now it looks like will be one more commit, based on recent discussion in gnome-shell.
I do not really know, without deeper digging in what is going on in gnome-shell. I got notice that commit with fix for my bug merged into master. I assume that current gnome-shell master should be working fine.
For next gnome-shell maintenance release, most likely will be one more commit for this bug.

**Comment by elpraga** [comment]
Any idea if that commit bubbles through into Ubuntu 20.04? It will be with us for 5 years..

**Comment by scherepanov** [comment]
No idea if it will get into Ubuntu 20.04

**Comment by uframer** [comment]
Can we work around this in gTile? I'm using Ubuntu 20.04 with gnome 3.36.2. It's really annoying and I don't want to disable gTile.

**Comment by scherepanov** [comment]
Created #137 
It will be a little but ugly but will be no crashes on Ubuntu 20.04

**Comment by scherepanov** [comment]
Please try on Ubuntu 20.04
https://github.com/scherepanov/gTile.git
If possible, better upgrade gnome-shell to 3.36.2-3 and above, this seems to be fixes bug.

**Comment by yochananmarqos** [comment]
@scherepanov GNOME Shell still crashes locking the screen using your branch on Manjaro using `gnome-shell` 1:3.36.2+7+ge4199c71c-1.

**Comment by scherepanov** [comment]
It is too bad that gnome-shell still crashing with gTile from my branch
Tweaking rest of styling will make gTile unusable, it will not show up on a screen at all.
May be fix is not possible. Bug in gnome-shell libst-1.0 is about first removing styling, and then editing signal about styling change. As result, client access structure that already been removed. If heap management already allocated memory to someone else, we will have a crash.
That is why bug behavior is unpredictable. On my machine crash happens always on second lock, while other see it on first lock.

But, let's do our due and try to produce workaround. At least I can say I tried.
I can no longer reproduce crash in my environment. Please copy here all long stack trace, including javascript, from your journalctl. I will check if additional fix is possible.

**Comment by yochananmarqos** [comment]
With the `gnome-shell` 1:3.36.3-1 update, the issue is resolved.

**Comment by sethgoldin** [comment]
Can confirm that on Fedora 32, with `gdm.x86_64 1:3.36.2-2.fc32`, everything's working great again--no crashing after attempting a second lock.

**Comment by sammo** [comment]
It always crashes on my ubuntu 20.04 with gnome-shell 3.36.4

**Comment by rj-david** [comment]
Crashes when laptop suspends

Ubuntu 20.04
gnome 3.36.3
